### ISSUE TITLE
Add support for PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE

### ISSUE THREAD

**Issue by linknetx** [kodi-pvr/pvr.dvblink#118]
Please add support for timer type capability PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE. At the moment the addon uses, or more correctly misuses, "Delete"/"Delete Timer" to disable a timer generated by a record series timer rule. In Kodi this means that the context menu for a previously disabled timer still shows the "Delete"/"Delete Timer" option which of course doesn't function.

With PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE implemented Kodi would show a context menu with the options "Deactivate" or "Activate" to allow the disabling or enabling of the relevant timer.

Unfortunately there is no reliable fix in Kodi possible as detailed here: https://github.com/xbmc/xbmc/pull/15659

Therefore, I kindly request that the maintainer of this addon adds support for PVR_TIMER_TYPE_SUPPORTS_ENABLE_DISABLE so that this issue in Kodi can be fixed.

**This shows the current problem;**

![1](https://user-images.githubusercontent.com/25765532/53720332-67247f00-3e58-11e9-9c06-3e7b62189d67.png)
![2](https://user-images.githubusercontent.com/25765532/53720336-6be93300-3e58-11e9-8d9d-47b9b137c113.png)

**This is how it would be with the requested option implemented:**

![3](https://user-images.githubusercontent.com/25765532/53720462-be2a5400-3e58-11e9-8d57-2f9872a530e9.png)
![4](https://user-images.githubusercontent.com/25765532/53720476-c4203500-3e58-11e9-808c-e6afbf584e69.png)

**Comment by linknetx** [comment]
**This shows the current problem;**

![1](https://user-images.githubusercontent.com/25765532/53720332-67247f00-3e58-11e9-9c06-3e7b62189d67.png)
![2](https://user-images.githubusercontent.com/25765532/53720336-6be93300-3e58-11e9-8d9d-47b9b137c113.png)

**This is with the requested option implemented:**

![3](https://user-images.githubusercontent.com/25765532/53720462-be2a5400-3e58-11e9-8d57-2f9872a530e9.png)
![4](https://user-images.githubusercontent.com/25765532/53720476-c4203500-3e58-11e9-808c-e6afbf584e69.png)

**Comment by dvblogic** [comment]
Fixed in pull request #119
