### ISSUE TITLE
 'Exception caught on main loop exiting' on live TV PVR

### ISSUE THREAD

**Issue by ace20022** [kodi-pvr/pvr.dvblink#34]
forum thread: http://forum.kodi.tv/showthread.php?tid=255618

**Comment by Jalle19** [comment]
@ace20022 is this still an issue?

**Comment by ace20022** [comment]
@Jalle19 not sure, I only created this issue for MarBe, cf. the forum thread

**Comment by Jalle19** [comment]
I will assume it's been fixed then since there was no updates in the forum thread since Jarvis Beta.
