### ISSUE TITLE
PVR_TIMER.iClientIndex handling bug

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.dvblink#58]
Problem description here: http://forum.kodi.tv/showthread.php?tid=291649&pid=2428317#pid2428317

Log here: http://forum.kodi.tv/showthread.php?tid=291649&pid=2428378#pid2428378

Problem in pvr.dvblink is around here i guess: https://github.com/kodi-pvr/pvr.dvblink/blob/master/src/DVBLinkClient.cpp#L827

 Cause: PVR_TIMER.iClientIndex must not change across different calls to GetTimers(...) as this index is used by Kodi core to re-identify timers: https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/timers/PVRTimers.cpp#L156

This is nothing new for Krypton - has been always like this.

ping @dvblogic

**Comment by dvblogic** [comment]
@ksooo This one is really difficult as all our indices are strings, not integers.
Should iClientIndex and iParentClientIndex be the same for the same schedules across Kodi start-up and shutdown cycles or only while Kodi is running?
If the latter, we can build a run-time map of our timer string ids to their kodi integer counterparts.

**Comment by ksooo** [comment]
The latter is sufficient. The index must not change as long as Kodi is running.

**Comment by dvblogic** [comment]
@ksooo Super. Thanks!

**Comment by Jalle19** [comment]
@dvblogic pvr.vbox has a ghetto string to unique integer utility function, you might want to utiluze that.

**Comment by dvblogic** [comment]
@ksooo Fixed the issue in pull requests #59 and #60 (Krypton and Jarvis respectively)

**Comment by ksooo** [comment]
@dvblogic cool. just merged the Jarvis pr. Krypton pr not yet merged. Please see my (very minor) comment.

**Comment by ksooo** [comment]
fixed with #61
