### ISSUE TITLE
[Kodi 17.0 Krypton] Lock-up on RecTV and Tuning Channel after Idle

### ISSUE THREAD

**Issue by ioguy** [kodi-pvr/pvr.dvblink#64]
After about 6h of idle time, Kodi locks up solid (no useful log) when you first try to enter the Recorded TV section or tune a channel in the guide.  Repeatable on LibreElec Generic and Windows 10.

Only occurs with Kodi 17 (all dev versions and final), no issues on 16.  Running latest addon version 3.3.11.1.  No issue when using different PVR backend.

See dvblink forum for additional details and others with the same issue:
https://forum.dvblogic.com/viewtopic.php?f=66&t=31841

**Comment by ferni7** [comment]
Getting the same issue, let me know if you need any logs/details.

**Comment by dvblogic** [comment]
Seems to be fixed finally.
