### ISSUE TITLE
[Kodi 17.0 Krypton]  Prevent duplicate episodes default setting not utilised

### ISSUE THREAD

**Issue by linknetx** [kodi-pvr/pvr.dvblink#65]
Kodi 17.0 Krypton on Windows 7
DVBLink Server 6.0.0 build 13310 on Windows 7
DVBLink TVSource 6.0.0 build 13310 on Windows 7

In the Kodi Settings menu there is an option to set the recording default for duplicate episodes with two options as shown below:

Settings / PVR & Live TV / Recording / Prevent duplicate episodes
Option 1: Record all episodes
Option 2: Record only new episodes

If this setting is changed to "Record only new episodes" then this is not used as the default setting when creating a new timer.

Selecting "Add Timer" from the EPG opens the "Timer Settings" dialogue box where the "Prevent duplicate episodes" option still shows "Record all episodes" and not the correct "Prevent duplicate episodes" setting.

**Comment by ksooo** [comment]
This is a Kodi core issue, nothing the add-on can fix.

**Comment by linknetx** [comment]
Ok, so can you please advise on where to post this issue.

Thanks

**Comment by ksooo** [comment]
trac.kodi.tv

**Comment by linknetx** [comment]
Ok, Thanks.

**Comment by linknetx** [comment]
As the Kodi Settings default option of "Prevent Duplicate Episodes" does not work I understand from @ksooo  that  is to be removed from the Kodi interface.

Therefore can I request that this option is added to the DBVLogic PVR Addon settings and used as the default when adding a new "Series Record Timer" in the Kodi interface.

I find that the option "Record only new episodes" is needed for all "Series Record Timers" to prevent duplicates and having to change to this every time I create a new recording is rather tedious.

**Comment by ksooo** [comment]
> I find that the option "Record only new episodes" is needed for all "Series Record Timers" to ...

Maybe a quick fix is that the addon sets the default to "record only new". => https://github.com/kodi-pvr/pvr.dvblink/blob/master/src/DVBLinkClient.cpp#L35

Next step could be to provide an addon setting where the user can choose the default values. This is done already today by pvr.hts. You can use this as reference implementation if you like.

**Comment by linknetx** [comment]
@dvblogic  any progress on this ?

**Comment by linknetx** [comment]
Thanks for the quick fix that the addon sets the default to "record only new" .

**Comment by beeeeswax** [comment]
While I'm really happy for linknetx that dvblogic saw fit to change a global default to fit his personal usage scenario, I'd like to point out that for some users, this is not the desired default and now _we_ must remember to change this setting for every recording.  Please can you add an option for this in the dvblink addon settings screen because forcing it either way is not desirable.
