### ISSUE TITLE
[Kodi 17.0 Krypton] Timer Rules incorrectly detected in DVBLink PVR Addon

### ISSUE THREAD

**Issue by linknetx** [kodi-pvr/pvr.dvblink#68]
Kodi 17.0 Krypton on Windows 7
DVBLink Server 6.0.0 build 13310 on Windows 7
DVBLink TVSource 6.0.0 build 13310 on Windows 7

**There is a problem with editing the timer rules in the Kodi "Timer Rules" screen.**

When editing both the "Repeating Manual Timer" and the "Repeating Keyword Based Timer" the resultant "Timer Settings" dialogue box shows these as being "Single Shot Manual Timers" which is not correct.

I have referred this to the Kodi team and their findings are that this is an addon issue as follows:

DVBLink addon's API function implementation of "GetTimers" does not set 'PVR_TIMER.iTimerType" correctly for "Repeating Manual Timer" (TIMER_REPEATING_MANUAL) and "Repeating Keyword Based Timer" (TIMER_REPEATING_KEYWORD).

**Comment by dvblogic** [comment]
The issue appears, because dvblink addon sets 
`timer.iEpgUid = PVR_TIMER_NO_EPG_UID;`
for timer rules. If we set a valid epgId then it "Timer Settings" dialogue box shows correct type of the timer rule.

@ksooo, I believe that Kodi behavior is incorrect here. The original epg event that was used to create a timer rule can be gone for a long time, but the rule still exists (which is perfectly correct).

**Comment by ksooo** [comment]
Could you please retest with latest Krypton or master build of Kodi? The issue should be solved there.

**Comment by dvblogic** [comment]
@ksooo Thanks. Will do. I am testing with Krypton 17.1RC at the moment

**Comment by ksooo** [comment]
Too old. :-)

**Comment by dvblogic** [comment]
@ksooo :) 
Is there any chance, if we commit dvblink pvr addon with all fixes (crash, hangup etc.) tomorrow, that it will end up in 17.1 release? Or it's too late already?

**Comment by ksooo** [comment]
commit everything, tag the release and open a pull request against the Krypton branch of repo-binary-addons

**Comment by ksooo** [comment]
And don't forget another PR against master . :-)

**Comment by dvblogic** [comment]
Yep, but Krypton will be first, master will follow a bit later

**Comment by linknetx** [comment]
I tested with the latest build, all of the timer rules are being detected correctly but before, with your last fix,  there were all five options to change to for each timer rule:

Option 1: Single Shot Manual Timer
Option 2: Single Shot EPG-based Timer
Option 3: Repeating Manual Timer
Option 4: Record Series Timer
Option 5: Repeating Keyword-Based Timer

Now it is as follows:

Option 1: Single Shot Manual Timer ------- (missing altogether)
Option 2: Single Shot EPG-based Timer
Option 3: Repeating Manual Timer ------- (missing altogether)
Option 4: Record Series Timer
Option 5: Repeating Keyword-Based Timer -------- (this is duplicated in it's own options)

**Comment by ksooo** [comment]
You know what? I think it's time that you start debugging Kodi on your own. ;-) I don't have the time to look up all things for you and compared to you I don't get a single Cent for all this. Although it might be Kodi bugs they only seem to appear with dvblink addon - so I actually don't care much to be really very honest ;-)

**Comment by ksooo** [comment]
Hint 1: https://github.com/kodi-pvr/pvr.dvblink/blob/master/src/DVBLinkClient.cpp#L353 => PVR_TIMER_TYPE_FORBIDS_EPG_TAG_ON_CREATE means the type cannot be created if an epg tag was supplied with the current timer info tag. So, if you select "Edit timer" from the context menu of an epg event, the current type of the timer cannot be changed to a type having this flag, thus it does not appear in the types list of the timer settings dialog. This is the direct result of what you stated with your timer type definition.

**Comment by dvblogic** [comment]
So, you actually do care a little bit ;)
Thanks for the hint. Will have a look tomorrow at it.

**Comment by ksooo** [comment]
I don't understand what you mean with "(this is duplicated in it's own options)". Does the type appear twice in the types list or what is wrong?

**Comment by ksooo** [comment]
Hint 2: I think just removing PVR_TIMER_TYPE_FORBIDS_EPG_TAG_ON_CREATE should solve the problem with the missing manual timer types. There is imo no point in setting this flag.

**Comment by linknetx** [comment]
Option 5: Repeating Keyword-Based Timer -------- (this is duplicated in it's own options)

What I meant was that when editing the "Repeating Keyword-Based Timer" the "Repeating Keyword-Based Timer" option is shown twice. 

I'm sorry but I can't make head nor tail of this any more,

The "Repeating Keyword-Based Timer" dialogue box doesn't show any of the additional settings relating to any of the timer types.

Of the two duplicate options for timer types, one is highlighted in blue indicating the type already selected, and one in white.

Selecting the white "Repeating Keyword-Based Timer" changes the dialogue box additional options to those of a correct "Repeating Keyword-Based Timer" dialogue box.

**Comment by ksooo** [comment]
As I said, I think it's time that you learn how to debug Kodi. I cannot (and don't want to) do the job for you, especially as I can only do "brain debugging". I do not even have the equipment to reproduce this.

**Comment by linknetx** [comment]
That would mean learning C/C++, or whatever language it's written in, from scratch !

You've solved the other problem about missing information which concerned me and I'm grateful for, but  these further bugs I only reported for completeness. I only ever use the Record Series timers so they don't really bother me ! 

The KodiSetup-20170225-c4c655489c-Krypton build was reasonable so perhaps just revert to that.

Regards

**Comment by ksooo** [comment]
> That would mean learning C/C++, or whatever language it's written in, from scratch !

@linknetx oops. I was not aware that it was you posting this. I thought it was @dvblogic and wanted to "encourage" him to do his job, not you. Sorry.

> The KodiSetup-20170225-c4c655489c-Krypton build was reasonable so perhaps just revert to that.

 Actually it was not. As you have stated yourself (iirc), changing a timer type afterwards ("Edit timer") did not work correctly.

**Comment by linknetx** [comment]
@ksooo No problem, just a misunderstanding since this thread has become somewhat confusing !!

**Comment by linknetx** [comment]
@dvblogic Testing this with Kodi build KodiSetup-20170303-e0a6f4cd9a-Krypton it would seem that these changes have been merged but issues still remain:

A minor point - the DBVLink addon still reports version 3.3.13 should this be 3.4.0 ?

The timer types are now being detected correctly but three of the "Edit Timer Rules" selection boxes are still incorrect:

1: Single Shot Manual Timer ------------- Incorrect
2: Single Shot EPG-based Timer --------- Okay
3: Repeating Manual Timer -------------- Incorrect
4: Record Series Timer ------------------- Okay
5: Repeating Keyword-Based Timer ----- Incorrect

Check out these commented screenshots for details:

![1 single shot manual timer](https://cloud.githubusercontent.com/assets/25765532/23856860/f4ebd53e-07f2-11e7-90d9-0d495e89bfc2.png)

![2 single shot epg based timer](https://cloud.githubusercontent.com/assets/25765532/23856875/04176c62-07f3-11e7-8b10-33b3e7e39a67.png)

![3 repeating manual timer](https://cloud.githubusercontent.com/assets/25765532/23856889/0a0ffcd8-07f3-11e7-80b7-50b6274dff34.png)

![4 record series timer](https://cloud.githubusercontent.com/assets/25765532/23856895/0e9387ca-07f3-11e7-9515-de49a524cd09.png)

![5 repeating keyword-based timer](https://cloud.githubusercontent.com/assets/25765532/23856898/12d65fd8-07f3-11e7-8e90-9dfcfea597ee.png)

It is a similar error in all three with a duplicate highlighted item added to the bottom of the lists.

@ksooo is this part of the Kodi interface or is it for dvblogic to fix ?

**Comment by dvblogic** [comment]
The issue is related to the fact that pvr.dvblink uses different types (e.g. different set of attributes) for new and already created timer rules. It was originally done, because dvblink backend does not support editing of some timer rules' attributes once timer rule was created (for example, changing channel or start/end time for manual once timer).
As timer rules' types are different, kodi cannot find a match and inserts extra row with a new type.
We have removed the extra types for now, which will make the whole thing to appear correctly in editing dialog.
However, because some of the attributes are not editable after creation, the changes to them will not be saved on ok.

**Comment by linknetx** [comment]
Thanks for the explanation, as long as the whole thing appears correct then that should be fine, after using it for a few times it will soon be clear which of the attributes are not being saved. It's then easy enough to delete it completely and create a new timer rule with the required attributes.

Will this update be in the next Kodi nightly build ?

**Comment by dvblogic** [comment]
Yep. Should appear in the nightly tonight.

**Comment by linknetx** [comment]
That's a lot better! 

There just seems to be one small anomaly remaining:

When creating a "Repeating Manual Timer" the "Days of The Week" setting is supported and works quite well. However, when editing the same rule the "Days of The Week" field is blank and does not pick up the value set when the rule was created.

I would have expected the value to be displayed even though, as you have explained, this must be one of the attributes which is not saved when editing the timer rule.

This is needed to be displayed because the edit timer rule facility can also be used just to check which settings were used during the rule creation. So if a rule is not recording as expected then the edit timer rule can be used to check the settings long after the rule creator has forgotten what was actually set.

**Screenshot:**
![missing](https://cloud.githubusercontent.com/assets/25765532/23653156/6354a6ba-0323-11e7-9535-4d477d1a1a81.png)

**Comment by linknetx** [comment]
@dvblogic  Any progress on this final issue ?

**Comment by linknetx** [comment]
@dvblogic is there anybody out there!

It would be nice to have this final issue resolved.

**Comment by dvblogic** [comment]
We will look into that

**Comment by linknetx** [comment]
@dvblogic Issue resolved, Thanks.
