### ISSUE TITLE
Hang while playing recording and pressing Next or Previous

### ISSUE THREAD

**Issue by hugegreenbug** [kodi-pvr/pvr.dvblink#76]
Issue:
While playing a recording in Krypton and if I press the next or previous buttons, Kodi will hang.

How to reproduce:
Play a recording
Show OSD
Click Next or Previous buttons

**Comment by dvblogic** [comment]
@ksooo Is this something for Kodi team? I checked under debugger and hangup is not in addon code, but somewhere in Kodi. I suspect that it also happens with other addons. Thanks.

**Comment by ksooo** [comment]
Please supply stack traces for the hang, then I can take a closer look. Otherwise I have no chance.

**Comment by hugegreenbug** [comment]
@ksooo Here is a stack trace after I force quitted it in MacOS: https://pastebin.com/KzYNb4rJ

**Comment by hugegreenbug** [comment]
@ksooo Another user reported this for tvheadend: https://forum.libreelec.tv/thread-6195.html

**Comment by ksooo** [comment]
@FernetMenta fyi. 100% reproducable on my Mac, with exactly the stacks supplied in in this issue. videoplayer::process does not exit, because videoplayervideo::process does not exit, for reasons unknown to me. On latest kodi master, this is.

**Comment by dvblogic** [comment]
@ksooo Can you, please, suggest if this issue can be closed here?.. I do not know if we can do anything about it.

**Comment by hugegreenbug** [comment]
@dvblogic, it's been fixed upstream, so I think you can close it.

Hugh
