### ISSUE TITLE
First TV channel is not shown in Timeline view, but is present in all other views

### ISSUE THREAD

**Issue by dvblogic** [kodi-pvr/pvr.dvblink#81]

**Comment by dvblogic** [comment]
@ksooo 
Need your help, please.
Does iUniqueId in PVR_CHANNEL have a special meaning when it equals to 0?

Channel with this iUniqueId is not shown in the Guide (Timeline) view, but is shown in all others - Channels, dialogs for adding timers etc.

**Comment by ksooo** [comment]
Zero is a valid channel uid.

PVR_CHANNEL_INVALID_UID (-1) is to be used to debote an invalid channel uid => https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_pvr_types.h#L169

EDIT: I'm not aware of any special handling of uid 0 in timeline view code, btw.

**Comment by dvblogic** [comment]
Then it is a bug in Kodi's Guide view

**Comment by ksooo** [comment]
Point me to the buggy source code line or it's not true. :-/
