### ISSUE TITLE
Missing compatibility with API 5.5.0?

### ISSUE THREAD

**Issue by debutanker** [kodi-pvr/pvr.dvblink#94]
Since Milhouse #0804 - Kodi version (18.0-ALPHA1 Git:dde9b24)  Platform: Linux x86 64-bit, DVBLink Addon doesn't start anymore (can't load shared library) ----> http://sprunge.us/QaEG .
Seems that further changes in pvr API ( https://github.com/xbmc/xbmc/pull/12609 ) caused the broken dvblink addon. Maybe some updates in the addon are required?

**Comment by ksooo** [comment]
> Maybe some updates in the addon are required?

 Definitely. It's up to the addon maintainer to do this.

**Comment by Jalle19** [comment]
ping @dvblogic

**Comment by dvblogic** [comment]
@Jalle19 Thanks. We will have a look next week.
