### ISSUE TITLE
[Kodi 17.6 Krypton] Prevent duplicate episodes default not configurable

### ISSUE THREAD

**Issue by beeeeswax** [kodi-pvr/pvr.dvblink#98]
The original default setting for "prevent duplicates" (prior to 17.1) always worked fine for me but it seems after just one user requested that this be changed [https://github.com/kodi-pvr/pvr.dvblink/issues/65](url) you obliged without adding an option for people happy with the previous configuration.

Please either roll this back or add an option in the DVBLink addon config screen.

**Comment by beeeeswax** [comment]
The problem remains the same in Kodi 18.x alpha and nightlies.

**Comment by linknetx** [comment]
@beeeeswax 

I'm the user who put in a request for an option for the user to be able to set the 'Prevent duplicate episodes' default setting. However DVBLogic opted for the easy option and just changed the default with no means of the user changing it back. This wasn't the requested result.

So I've just sent them a Pull Request 'Addon default record show type option setting #111' which adds this option.

If you're still interested in this then perhaps you could also follow it up with them to try and get it merged.

**Comment by dvblogic** [comment]
fixed in addon version 4.7.1
